CREATE PROCEDURE [dbo].[usp_AuditLog_INS]
	@Message VARCHAR(MAX)
AS
SET NOCOUNT ON SET XACT_ABORT ON;
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN

	INSERT INTO dbo.tblAuditLog(AuditDesc, CreatedOn)
	VALUES (@Message, GETDATE())

END
